[package]
name = "zeitig"
version = "0.1.0"
authors = ["Leopold Luley <git@leopoldluley.de>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.106", features = ["derive", "rc"] }
serde_yaml = "0.8.11"
time = { version = "0.2.15", features = ["serde"] }

[dependencies.druid]
git = "https://github.com/xi-editor/druid"

[dependencies.match_macro]
git = "https://github.com/finnerale/druid-enum-helpers"
package = "match-macro"
